In [36]:
import numpy as np
import numpy.matlib
##basic sudoku format
##even though matlib can be used to reclassify these arrays as matrices, the matrix format might be removed from numpy in the future

standard= np.array(np.mat('[1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9; 1 2 3 4 5 6 7 8 9]'))

##class to bold specific nums in question:

class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

##matrix creation of 0's in standard sudoku format:
## we save the grid of a particular puzzle to a variable:
### The sudopuzzle grid is not a true puzzle, as it already breaks the puzzle requirements (same number lies on the same row/column). 
#### It is there for referencing columns and rows once it is transformed

##sample sudo puzzle

grid = [[5,3,0,0,7,0,0,0,0],
       [6, 0, 0, 1, 9, 5, 0, 0, 0],
       [0, 9, 8, 0, 0, 0, 0, 6, 0],
       [8, 0, 0, 0, 6, 0, 0, 0, 3],
       [4, 0, 0, 8, 0, 3, 0, 0, 1],
       [7, 0, 0, 0, 2, 0, 0, 0, 6],
       [0, 6, 0, 0, 0, 0, 2, 8, 0],
       [0, 0, 0, 4, 1, 9, 0, 0, 5],
       [0, 0, 0, 0, 8, 0, 0, 7, 9]]

grid = np.matrix(grid)
print(grid)

X = [num for num in range(1,10)]
Y = [3,2,4,5,7,6,9,8,1]
print()

print(len(np.unique(X)) == len(np.unique(Y)))

valid = []
print(np.array(sudo_puzzle))
    


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]

True
[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [55]:
import numpy as np
import numpy.matlib

def possible(y,x,n):
    global grid
    for i in range(0,9):
        n=grid[y][x]
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        n=grid[y][x]
        if grid[i][x] == n:
            return False
    x0= (x//3)*3
    y0= (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

    
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if 0 in grid[y][x]:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x]=n
                        solve()
                        grid[y][x]=0
                return 
    print(np.matrix(grid))
    input("More?")


    



    

In [56]:
solve()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
#we now define the rows and columns to respective variables:
def rower(puzzle):
    rows_arr= []
    print("""This function will output two different formats of column data: Sectioned by column and raw output.""")
    for rows in range(len(puzzle)):
        print(color.BOLD + "Row number {rows}: ".format(rows = rows) + color.END, puzzle[rows])
        rows_arr.append(puzzle[rows])
    rows_arr = np.array(rows_arr)
    return rows_arr.reshape(9,9)


#for columns in range(len(sudoku[rows]))

def columnizer(puzzle):
    column_arr=[]
    for row in range(len(puzzle)):
        for column in range(0,len(puzzle[row]),1):
            column_arr.append(puzzle[column][row])
    column_arr = np.array(column_arr)
    column_arr = column_arr.reshape(9,9)
    print("""This function will output two different formats of column data: Sectioned by column and raw output.""")
    for rows in range(len(column_arr)):
        print(color.BOLD + "Column number {column}: ".format(column = rows) + color.END, column_arr[rows])
    print("\n")  
    
    return(column_arr.reshape(9,9))
    
print("\n")
print("SECTIONED COLUMNS")
columnarray = columnizer(sudo_puzzle)
print("\n")
print("SECTIONED ROWS")
rows_puzzle = rower(sudo_puzzle)
print("\n")
print("RAW FORMAT COLUMN")
print(columnarray)
print("\n")
print("RAW FORMAT ROW")
print(rows_puzzle)
print("\n")

In [ ]:
##RULE SETS are needed to satisfy the puzzle requirements
###That is to say, each row and column of numbers must be a unique integer within 1-9 range. 
####Each 3x3 grid that divides up the grid uniformly must also carry unique integers within the 1-9 range
##### We will be using raw data 
###### We shall test each row and column for the row rule.
####### Right below are the empty dicts to input respective values in their categories for future use.
# correct_box = {}
# invalid_box = {}
# empty_box = {}
# def rcchecker(arr):
#     for rows in range(len(arr)):
#         for columns in range(len(arr[rows])):
#             if arr[rows][columns] == 0:
#                 correct_box[(rows,columns)] = arr[rows][columns]
#                 print("Number ", arr[rows][columns], ("on row {rows} on column {columns} needs a number for satisfaction").format(rows = rows, columns = columns))
#             elif (any(arr[rows]) == arr[rows][columns] or any(arr[columns] == arr[rows][columns])):
#                 invalid_box[(rows,columns)] = arr[rows][columns]
#                 print("Number ", arr[rows][columns], ("on row {rows} on column {columns} is invalid, as they share same numbers on the plane").format(arr = arr, rows = rows, columns = columns))
#             elif any(arr[rows]) != arr[rows][columns]:
#                 empty_box[(rows,columns)] = arr[rows][columns]
#                 print("Number ", arr[rows][columns], ("on row {rows} on column {columns} is correct").format(rows = rows, columns = columns))
#             else: 
#                 print(("Row {rows} on column {columns} value ERROR").format(rows = rows, columns = columns))

# checked = rcchecker(rows_puzzle)
# print("\n")
# checked                    

def RCcheck(arr):
    correct = {}
    empty = {}
    wrong = {}
    for row in range(len(arr)):
        for col in range(len(arr[row])):
            if arr[row][col] == 0:
                empty[(row,col)] = arr[row][col]
            elif arr[row][col] != arr[col][row] and sum(arr[row]) == 45 and sum(arr[col])
                wrong[(row,col)] = arr[row][col]
            
                correct[(row,col)] = arr[row][col]
    return correct, empty, wrong

print(RCcheck(sudo_puzzle))

In [ ]:
#Here we will recalls the dicts to make sure they've been corrected inputed into their respective boxes
print("CORRECT NUMS IN ROW COL")
print(correct_box) 
print("\n")
print("INVALID NUMS IN ROW COL")
print(invalid_box)
print("\n")

In [ ]:
###We can now construct a box checker for the 3x3 grids within sudoku that requires the same rules as columns and rows...
####Let's test out using numpy reshape method to re-grid it by those standards..

##### We will use a 9x9 indexed from 0 to 80. 

###### What we want is 3 rows and 3 column boxes, each box's rows have number values such that the second row indexes will be +=9 from the preceding row's three indexes.
####### like so...
######## Notice that for each column, the value of each descending row results in +9. 
# So we can use a set up in which block X = 3 row x 3 col values where for each row (col, col+1, col+2), append 3 values where col is = (row, row + 9, row + 18).
### BLOCK ZERO = ARRAY [COL, COL+1, COL+2 on ROW 0 = 0 1 2, COL,COL+1,COL+2 on ROW1 = 9 10 11, COL, COL+1, COL+2 on ROW3 = 18,19,20

#SO BLOCK 00 = [0 1 2][9 10 11][18,19,20]
####BLOCK 01 = [3 4 5][12 13 14][21 22 23]
####BLOCK 02 = [6 7 8][15 16 17][18 19 20]
###### So each block appends arr[values] such that where count = 3+=3(after each block):
###### block X = arr[X times 3 rows][X times COUNT : COUNT plus ROW] , arr[X+1][count:3*count+3], arr[X+2]
###### block 0 = arr[0 times 3][]
###### block 1 = arr[1 times 3][]
###### block 2 = arr[2 times 3][]

def boxGRIDmaker(arr):
    box_arr = []
    count = 0
    for rows in arr:
        box_arr.append(rows[:3])
    for rows in arr:
        box_arr.append(rows[3:6])
    for rows in arr:
        box_arr.append(rows[6:9])
    box_arr = np.array(box_arr).reshape(3,3,3,3)
    return box_arr


    ##X and Y represent ROW X --> Y. we want it to stay at row 0 -> 3 for the first three cycles. 
    ##W and Z for COLUMNS must constantly shift values by +1 per scan, +3 per cycle.  
    ##while the cycle has gone through less than 9 (9 boxes are needed)
    ##initial range should be 0-3, then 3-6, then 6-9
    ## for cycles 3-6, we got to make sure W and Z values reset to 0 and 3, looping again.
    ## so for cycle 3, W,Z must be 0,3 //cycle four: 3 to 6, cycle five, 6 to 9.
     ## BOX 1 initiate
        
print(boxGRIDmaker(sudo_puzzle))
for box in sudo_puzzle:
    print(box)
    


In [ ]:
arr = [1,2,3,4,5,6,7,8,9]

print(sum(arr))

In [ ]:
print(standard)
print(sum(standard[:][:]))
print("\n")
aggregate = 0
for row in range(len(standard)):
    for col in range(len(standard[row])):
        aggregate = sum(standard[row][col])
        print(aggregate)